### ISSUE TITLE
update pre-commit configuration

### ISSUE THREAD

**Issue by sgaunet** [sgaunet/template-cli#2]
```
  - repo: https://github.com/sgaunet/pre-commit
    rev: v0.2.0
    hooks:
    - id: osv-scanner
    - id: govulncheck
    - id: gitleaks
```
